// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyC9sMOpCfUu_f4QSo7jtsL_h_g3Lg2qhfE',
    appId: '1:261306101385:web:805e4428518f3d75472058',
    messagingSenderId: '261306101385',
    projectId: 'eventracrm',
    authDomain: 'eventracrm.firebaseapp.com',
    storageBucket: 'eventracrm.firebasestorage.app',
    measurementId: 'G-X3QGFJLQ7V',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAlb7AoD1H8FYxcwt9HSm8ZVnn6tGlyb9I',
    appId: '1:547155268093:android:a0815e5b5ef34522eb8994',
    messagingSenderId: '547155268093',
    projectId: 'inkspireblogapp',
    storageBucket: 'inkspireblogapp.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCnBqAJAsuIok2r5YQM8EXuri-wqcejUQI',
    appId: '1:261306101385:ios:0eb278a34cb07afc472058',
    messagingSenderId: '261306101385',
    projectId: 'eventracrm',
    storageBucket: 'eventracrm.firebasestorage.app',
    iosBundleId: 'com.example.testprojectsix',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCnBqAJAsuIok2r5YQM8EXuri-wqcejUQI',
    appId: '1:261306101385:ios:0eb278a34cb07afc472058',
    messagingSenderId: '261306101385',
    projectId: 'eventracrm',
    storageBucket: 'eventracrm.firebasestorage.app',
    iosBundleId: 'com.example.testprojectsix',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyC9sMOpCfUu_f4QSo7jtsL_h_g3Lg2qhfE',
    appId: '1:261306101385:web:81028871199ab32c472058',
    messagingSenderId: '261306101385',
    projectId: 'eventracrm',
    authDomain: 'eventracrm.firebaseapp.com',
    storageBucket: 'eventracrm.firebasestorage.app',
    measurementId: 'G-NTFVEG0F8D',
  );
}